print("Group 2's tech workshop ideas:")
print("Jessica: AI prompt engineering")
print("Vedant: Intro to Machine Learning")
print("Name: Idea")
print("Name: Idea")
print("Sean Gretzinger: How APIs Work")